---
title: "Opinion Policy Covid"
author: "Nate Breznau"
date: "5/18/2020"
output:
  html_document: default
---

Data setup/cleaning code for "Welfare State (Re)Assurance in Times of Crisis"
https://osf.io/muhdz/


```{r setup, warning=F, message=F}
# clean workspace
rm(list = ls(all = TRUE))
# packages
pacman::p_load("dplyr","countrycode","car","xlsx","jtools","tidyverse")



```

COVIDiSTRESS Data project


Andreas Lieberoth, Dominik-Borna Ćepulić, Jesper Rasmussen, Giovanni A. Travaglino, Jarno Tuominen
Available at: https://osf.io/z39us/ 

The most recent file was downloaded on 27-May-2020 from the above site

"COVIDiSTRESS global survey May 4 2020 (numeric values).csv" 

```{r data1, message = F, warning = F}


# The data has the first 3 rows occupied by text

# Import separate file for header
cishead <- read.csv(unzip(here::here("data/COVIDiSTRESS global survey May 25 2020 (numeric values).zip")), header = F, nrows=1, as.is = T)

# Now import numeric data

cis <- read.csv(unzip(here::here("data/COVIDiSTRESS global survey May 25 2020 (numeric values).zip")))

# Remove rows and rename headers (loop not working, do by hand for now)

cis <- cis[-c(1,2),]
colnames(cis) <- cishead

rm(cishead)

# The country names are only listed in the 'choice' files, extract them here 
cisc <- read.csv(unzip(here::here("data/COVIDiSTRESS global survey May 25 2020 (choice text).zip")))

cisc <- cisc[-c(1,2),]

cisc$cname <- cisc$Country

cisc <- select(cisc, ResponseId, cname)

# append country name to numeric data
cis <- left_join(cis,cisc, by = "ResponseId")

rm(cisc)

# get country codes and ISO letters
cis$cow  <- countrycode(cis$cname, "country.name", "cown")
cis$iso  <- countrycode(cis$cname, "country.name", "iso3c")


#need to adjust formats

cis <- cis %>%
mutate(Corona_concerns_1 = as.numeric(Corona_concerns_1),
       Corona_concerns_2 = as.numeric(Corona_concerns_2),
       Corona_concerns_3 = as.numeric(Corona_concerns_3),
       Corona_concerns_4 = as.numeric(Corona_concerns_4),
       Corona_concerns_5 = as.numeric(Corona_concerns_5),
       date = as.Date(EndDate))


#get case numbers by country (drop when too low)
cis <- cis %>% 
  group_by(cow) %>%
  mutate(cases = sum(!is.na(Corona_concerns_1))) %>%
  ungroup()


# Save files for easy import
save(cis, file = here::here("data/cis.Rdata"))
          
```
