---
title: "cis_rc28_gibbs"
author: "Hung HV Nguyen"
date: "8/25/2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls(all = T))

wd <- "C:/data" #set your working directory here

wdir <- function(x){
  paste(wd,x, sep = "/")
}
```

```{r savepoint}
load(df, file = wdir("COVIDiSTRESS/df_gibbs.Rmd"))
```


```{r sim3}

# Vertical simulation - 1000 observations for each country * 74 countries = 74000 obs.

df_new <- subset(df,select = c(concern_self, days_since_peak, conf_delta, as.vector(gov_resp), gini_disp, as.vector(cow), concern_self_se))



df_sim <- setNames(data.frame(matrix(ncol = 7, nrow = 74000)), c("concern_self", "dsp", "conf", "gov", "gini", "cntry", "concern_self_se"))

for (i in 1:7){
  df_sim[,i] = rep(df_new[,i],1000)
}

df_sim <- df_sim[order(df_sim$cntry),]
set.seed(167)

for (j in 1:nrow(df_sim)){
  df_sim[j,1] = rnorm(1, mean = df_sim[j,1], sd = df_sim[j,7])
}

hist(df_sim$concern_self)


# Gibbs sampling with RJAGS - run the model 15000 times from 74000 observations until y reaches its stationary distribution!


mod_string <- "model{
  for (i in 1:n){
    y[i] ~ dnorm(mu[i], prec)
    mu[i] = b[1] + b[2]*dsp[i] + b[3]*conf[i] + b[4]*gov[i] + b[5]*gini[i] + b[6]*cntry[i]
  }  
  for (j in 1:6) {
    b[j] ~ dnorm(0, 1/1e6) # non-informative prior
  }
  prec ~ dgamma(5/2, 5*10/2)
  sigma2 = 1/prec
  sigma = sqrt(sigma2)
}"

data_jags <- list(y = df_sim$concern_self, dsp = df_sim$dsp, conf = df_sim$conf, gov = df_sim$gov, gini = df_sim$gini, cntry = as.factor(df_sim$cntry), n = nrow(df_sim))

mod1 <- jags.model(textConnection(mod_string), data = data_jags, n.chains = 3) # 3 chains

update(mod1,1e3) ## burn-in 1000 iterations


params <- c("b","sigma")
mod_sim <- coda.samples(model = mod1, variable.names = params, n.iter = 5e3) #5*3 = 15000 iterations

mod_csim <- do.call(rbind,mod_sim)

summary(mod_sim)
effectiveSize(mod_sim)
plot(mod_sim)



# lm mod

mod2 <- lm(concern_self ~ dsp + conf + gov + gini + as.factor(cntry), data = df_sim)

summary(mod2)
```


